//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1434
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valil.Chess.Opponents.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Valil.Chess.Opponents.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opponent moving.
        /// </summary>
        internal static string AIMovingTitle {
            get {
                return ResourceManager.GetString("AIMovingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer vs You.
        /// </summary>
        internal static string ComputerVsYouText {
            get {
                return ResourceManager.GetString("ComputerVsYouText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two-player mode.
        /// </summary>
        internal static string TwoPlayerModeText {
            get {
                return ResourceManager.GetString("TwoPlayerModeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error connecting to the web service..
        /// </summary>
        internal static string WSConnectionErrorMsg {
            get {
                return ResourceManager.GetString("WSConnectionErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web service vs You.
        /// </summary>
        internal static string WSVsYouText {
            get {
                return ResourceManager.GetString("WSVsYouText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You vs Computer.
        /// </summary>
        internal static string YouVsComputerText {
            get {
                return ResourceManager.GetString("YouVsComputerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You vs Web Service.
        /// </summary>
        internal static string YouVsWSText {
            get {
                return ResourceManager.GetString("YouVsWSText", resourceCulture);
            }
        }
    }
}
