//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1434
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valil.Chess.WinFX.VisualElements.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RotatedBoard2D {
            get {
                return ((bool)(this["RotatedBoard2D"]));
            }
            set {
                this["RotatedBoard2D"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public int AnimationStartDelay {
            get {
                return ((int)(this["AnimationStartDelay"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int AnimationDurationBaseFactor {
            get {
                return ((int)(this["AnimationDurationBaseFactor"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int AnimationDurationScaleFactor {
            get {
                return ((int)(this["AnimationDurationScaleFactor"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public double Navigation3DAngleAccelerationFactor {
            get {
                return ((double)(this["Navigation3DAngleAccelerationFactor"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public double Navigation3DStepAngle {
            get {
                return ((double)(this["Navigation3DStepAngle"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.5")]
        public double Navigation3DStepDistance {
            get {
                return ((double)(this["Navigation3DStepDistance"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Identity")]
        public global::System.Windows.Media.Media3D.Quaternion ViewableGroupRotation3D {
            get {
                return ((global::System.Windows.Media.Media3D.Quaternion)(this["ViewableGroupRotation3D"]));
            }
            set {
                this["ViewableGroupRotation3D"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,0,50")]
        public global::System.Windows.Media.Media3D.Point3D CameraLocation3D {
            get {
                return ((global::System.Windows.Media.Media3D.Point3D)(this["CameraLocation3D"]));
            }
            set {
                this["CameraLocation3D"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,1,0")]
        public global::System.Windows.Media.Media3D.Vector3D CameraUpDirection3D {
            get {
                return ((global::System.Windows.Media.Media3D.Vector3D)(this["CameraUpDirection3D"]));
            }
            set {
                this["CameraUpDirection3D"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0,0,-50")]
        public global::System.Windows.Media.Media3D.Vector3D CameraLookDirection3D {
            get {
                return ((global::System.Windows.Media.Media3D.Vector3D)(this["CameraLookDirection3D"]));
            }
            set {
                this["CameraLookDirection3D"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Identity")]
        public global::System.Windows.Media.Media3D.Matrix3D CameraMatrix3D {
            get {
                return ((global::System.Windows.Media.Media3D.Matrix3D)(this["CameraMatrix3D"]));
            }
            set {
                this["CameraMatrix3D"] = value;
            }
        }
    }
}
